# Generated by Django 4.0.4 on 2022-05-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('first_answer', models.CharField(max_length=200)),
                ('second_answer', models.CharField(max_length=200)),
                ('third_answer', models.CharField(max_length=200)),
                ('fourth_answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('quant', models.IntegerField()),
            ],
        ),
    ]
