# Generated by Django 4.0.4 on 2022-05-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplication_table_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='shortcut',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
    ]
