# Generated by Django 4.0.4 on 2022-05-15 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiplication_table_app', '0002_test_shortcut'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
