# Generated by Django 4.0.4 on 2022-05-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplication_table_app', '0003_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='questions_field',
            field=models.CharField(default='default', max_length=2000),
            preserve_default=False,
        ),
    ]
