# Generated by Django 4.0.4 on 2022-05-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplication_table_app', '0004_test_questions_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='questions_field',
            field=models.CharField(max_length=65536),
        ),
    ]
