# Generated by Django 4.0.4 on 2022-05-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplication_table_app', '0005_alter_test_questions_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='questions_field',
            field=models.BinaryField(),
        ),
    ]
